### ISSUE TITLE
When loading materialdesignicons-webfont Google Chrome is freezing.

### ISSUE THREAD

**Issue by AMVAlex** [andreinitescu/IconFont2Code#3] opened 2019-10-27 07:11 UTC
Hello. I'm using Google Chrome Version 78.0.3904.70 (Official Build) (64-bit) on macOS Mojave. After I upload materialdesignicons-webfont.ttf the site becomes unresponsive (freezing) and it doesn't trigger other click events. 
On Safari it works perfectly.
Thanks for awesome project ;)
[materialdesignicons-webfont.ttf.zip](https://github.com/andreinitescu/IconFont2Code/files/3775586/materialdesignicons-webfont.ttf.zip)

**Comment by andreinitescu** [comment] 2019-10-27 10:11
Hi Alex, 

Thanks a lot for reporting this.
I pushed a new version which should fix the issue.

Unfortunately I had to disable C# syntax highlighting which was causing the freeze (it seems like PrismJS has an issue). I haven't found the cause of the problem, if someone knows, it'd be great to fix this. Why can't we have nice things in life easier?

**Comment by andreinitescu** [comment] 2019-10-27 10:12
I'm closing this, please reopen if it doesn't work for you. Thanks

**Closed as completed by andreinitescu** 2019-10-27 10:12 UTC

**Comment by andreinitescu** [comment] 2021-01-08 13:08
Just a friendly reminder, if you think it's worth it, you can always buy me a coffee ☕ There's a donate buton on the page. Thanks!
